//single todo crud
export const POST_TODO_START = 'POST_TODO_START';
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS';
export const POST_TODO_FAILURE = 'POST_TODO_FAILURE';

export const DELETE_TODO_START = 'DELETE_TODO_START';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

export const UPDATE_TODO_START = 'UPDATE_TODO_START';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE';

//fetch all todosApi
export const FETCH_TODOS_START = 'FETCH_TODOS_START';
// export const FETCHING_TODOS = 'FETCHING_TODOS';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

//errors
export const SHOW_ERROR_NOTIFICATION = 'SHOW_ERROR_NOTIFICATION';
export const HIDE_ERROR_NOTIFICATION = 'HIDE_ERROR_NOTIFICATION';

//data pending
export const DATA_PENDING_START = 'DATA_PENDING_START';
export const DATA_PENDING_FINISHED = 'DATA_PENDING_FINISHED';

